### ISSUE TITLE
Latest version 0.4.0 available  on the marketplace for Liferay CE Portal 7.0 GA3+ ?

### ISSUE THREAD

**Issue by rambocloack** [finalist/liferay-oidc-plugin#19]
Hi,

I use actually this plugin (version 0.2.2) on my liferay 7.0GA3+.
I want to use the SSO Logout functionnality which is implemented in latest version 0.4.0.
Please, can you commit this latest version for liferay 7.0.GA3+ on the marketplace ?

Thanks in advance.

**Comment by gvanderploeg** [comment]
Great to hear that you use the plugin.
As a rule of thumb we only support the latest versions of each major portal version, to keep things simple when testing/reporting.
Is there a reason for not updating to GA5? (I'm not using CE myself, so I'm not that familiar updating a CE instance)
