### ISSUE TITLE
Facing issue with org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.net.UnknownHostException: www.googleapis.com

### ISSUE THREAD

**Issue by karthikreddym** [finalist/liferay-oidc-plugin#23]
Dear All,

  I have deployed the lpkg file and configured the below properties

openidconnect.enableOpenIDConnect=true
openidconnect.token-location=https://www.googleapis.com/oauth2/v4/token
openidconnect.authorization-location=https://accounts.google.com/o/oauth2/v2/auth
openidconnect.profile-uri=https://www.googleapis.com/plus/v1/people/me/openIdConnect
openidconnect.issuer=https://accounts.google.com
openidconnect.client-id=ID got from google when I registered
openidconnect.secret=Secret Key updated with new value
openidconnect.scope=openid profile email

Here other than client-id and secret remaining values I updated as it is portal-ext.properties. Once if deploy the plugin I am able to see output as successfully deployed and it is showing under All Apps
But here it is showing as **There are no configurable plugins for this app.**
![image](https://user-images.githubusercontent.com/6309043/36775569-a599e33a-1c88-11e8-9eb6-0cd7c70c607f.png)
I am not getting when I click on sign in or where I can see this plugin.
Below errors I a facing 

org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.net.UnknownHostException: www.googleapis.com
	at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:108)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55)
	at nl.finalist.liferay.oidc.OpenIDConnectFilter.exchangeCodeForAccessToken(OpenIDConnectFilter.java:162)
	... 27 more
Caused by: java.net.UnknownHostException: www.googleapis.com

So Please provide me the working testing values for portal-ext.properties to verify and please let me know if I need modify any other configuration here.

Thanks & Regards,
   Karthik

**Comment by gvanderploeg** [comment]
Apparently your liferay server has no internet access? The protocol OpenID Connect only works if the client (Liferay in this case) can verify the access/id token with the OpenID Provider (google in this case) directly using a 'back channel'. Either let the Liferay server connect to the internet freely or at least provide DNS resolution for www.googleapis.com and let the server connect to that/those addresses on TCP port 443.
