### ISSUE TITLE
get OpenIDConnectUserInfo in session from post login hooks

### ISSUE THREAD

**Issue by robertotacchi72** [finalist/liferay-oidc-plugin#27]
Hi,
I 've been able to connect my liferay with an identity provider using your plugin. I need to associate the related groups with the LF user . I developed a post login hooks to get the object OpenIDConnectUserInfo in session as follows:

@Component(
    immediate = true, 
    property = { "key=login.events.post" }, 
    service = LifecycleAction.class
)
public class MyPostLogin implements LifecycleAction {

	@Override
	public void processLifecycleEvent(LifecycleEvent lifecycleEvent) throws ActionException {

		final HttpSession session = lifecycleEvent.getRequest().getSession();

		  Map <String, String> userInfo = (Map <String, String>) session.getAttribute ("OpenIDConnectUserInfo");
		
		if (userInfo != null) {
			// add user group
		}
	}

}

but I get a null value . 
How can I get user information from the identity provider (keycloak in my case) in my post login hook to add custom logic ?
Thanks.
Roberto

**Comment by gvanderploeg** [comment]
Good question.
Right now I don't have a setup with DXP that does the same as what you try to achieve. But I agree that this is exactly the way we intended it to work.
In a related 6.2 setup we had to work with these portal properties:

    # These are the defaults
    session.enable.phishing.protection=true
    session.phishing.protected.attributes=CAS_LOGIN,HTTPS_INITIAL,LAST_PATH

I'd suggest you add the session attribute ``OpenIDConnectUserInfo`` to this list and try again?

**Comment by gvanderploeg** [comment]
> I added the session attribute OpenIDConnectUserInfo to list as you suggested and it works.

Good to hear that this works in practice.

> How the plugin behave on HTTPS protocol.

Nothing special there. The only thing to make sure is that URLs are sensitive to the protocol name; that is: if configured endpoint and/or allowed redirect uris are http-urls instead of https, they will only work on http, not https. In other words: make sure all urls are properly changed to https when using https.
