### ISSUE TITLE
No issue, working as intended.

### ISSUE THREAD

**Issue by devildog820** [finalist/liferay-oidc-plugin#30]
There is no issue here.

**Comment by rambocloack** [comment]
Je suis absent(e) du bureau jusqu'au 24/08/2018

Bonjour,

Je suis absent du 06/08/2018 au 24/08/2018.
Je répondrais à votre message dès mon retour.
Pour toutes demandes merci de bien vouloir vous adresser au
Support-Technique Isocel par mail à l'adresse suivante:
support-technique.isocel@isocel.info ou par téléphone au 0524549961.

Cordialement Richard AMBAUD


Remarque : ceci est une réponse automatique à votre message  "Re:
[finalist/liferay-oidc-plugin] No issue, working as intended. (#30)" envoyé
le 06/08/2018 20:14:53.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

**Comment by rambocloack** [comment]
Je suis absent(e) du bureau jusqu'au 24/08/2018

Bonjour,

Je suis absent du 06/08/2018 au 24/08/2018.
Je répondrais à votre message dès mon retour.
Pour toutes demandes merci de bien vouloir vous adresser au
Support-Technique Isocel par mail à l'adresse suivante:
support-technique.isocel@isocel.info ou par téléphone au 0524549961.

Cordialement Richard AMBAUD


Remarque : ceci est une réponse automatique à votre message
"[finalist/liferay-oidc-plugin] Landing Page in portal-ext being ignored
(#30)" envoyé le 06/08/2018 19:42:54.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.
