### ISSUE TITLE
Offline maven repository prevents compilation

### ISSUE THREAD

**Issue by nicolasriousset** [finalist/liferay-oidc-plugin#40]
Hi,

I'm trying to compile the plugin oidc plugin source code, but an error occurs when retrieving the parent POM of the OIDC-parent project :
`    <parent>
        <groupId>nl.iprofs.pom</groupId>
        <artifactId>parent</artifactId>
        <version>2.0.25</version>
    </parent>
`
It seems the repository https://nexus.iprofs.nl/content/repositories/releases-public is not available. Is it temporary or permanent ? Is there another repository that could be used ?

Thank you very much,

Nicolas

**Comment by gvanderploeg** [comment]
Thanks Nicolas, for bringing our attention to it. We're looking into it. The root cause is that this artifact repository has been decommissioned but the replacement has yet to be added in this POM. We'll come with a commit for this shortly.

-Geert

**Comment by nicolasriousset** [comment]
Thank you for your quick answer Geert, I'll wait for the replacement repository.

Nicolas

**Comment by gvanderploeg** [comment]
Fixed, removed parent pom reference altogether.
