### ISSUE TITLE
Login exception with custom login module

### ISSUE THREAD

**Issue by gustavocampos** [finalist/liferay-oidc-plugin#41]
My Liferay installation has a custom JAAS login module and I kept getting login exceptions on portal and jboss classes after a successful Azure login.

On trial and error I found the problem at this line in LibAutoLogin.java:
userResponse = new String[]{userId, UUID.randomUUID().toString(), "false"};

I couldn't find any info about setting the last parameter as true or false, but setting it as false doesn't trigger my custom login module defined on portal.jaas.impl property.

**Comment by gustavocampos** [comment]
Just found out that the last parameter is regarding to the user password, which I have replaced in for your UUID, true for encrypted, false for unencrypted...

**Comment by rambocloack** [comment]
Je suis absent(e) du bureau jusqu'au 10/08/2019

Bonjour,

Je suis absent du  22/07/2019 au 10/08/2019.
Je répondrais à votre message dès mon retour.
Pour toutes demandes merci de bien vouloir vous adresser au
Support-Technique Isocel par mail à l'adresse suivante:
support-technique.isocel@isocel.info ou par téléphone au 0524549961.

Cordialement Richard AMBAUD


Remarque : ceci est une réponse automatique à votre message  "Re:
[finalist/liferay-oidc-plugin] Login exception with custom login module
(#41)" envoyé le 06/08/2019 23:43:01.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

**Comment by rambocloack** [comment]
Je suis absent(e) du bureau jusqu'au 10/08/2019

Bonjour,

Je suis absent du  22/07/2019 au 10/08/2019.
Je répondrais à votre message dès mon retour.
Pour toutes demandes merci de bien vouloir vous adresser au
Support-Technique Isocel par mail à l'adresse suivante:
support-technique.isocel@isocel.info ou par téléphone au 0524549961.

Cordialement Richard AMBAUD


Remarque : ceci est une réponse automatique à votre message
"[finalist/liferay-oidc-plugin] Login exception with custom login module
(#41)" envoyé le 06/08/2019 22:53:18.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

**Comment by gvanderploeg** [comment]
Although I fully welcome issues and suggestions, I don't understand whether there is an actual problem here. Will close this issue if no further comments are added.

**Comment by gustavocampos** [comment]
As far as I could understand, Liferay 6.2 requires any user to have a password besides the user being authenticated elsewhere, so I had to generate a random password when creating a user that comes from Azure, also I had to send this password to authenticate on Liferay, your code sends a random UUID as the password.

So what I did was: userResponse = new String[]{userId, userPassword, "true"};
userPassword is the encrypted random generated password retrieved from the database.
