### ISSUE TITLE
troubles with travis

### ISSUE THREAD

**Issue by ricsxn** [finalist/liferay-oidc-plugin#42]
I experienced problems with travis while attempting to push some changes in my own fork of this plugin. It seems the original oraclejdk8 entry is no longer supported by travis.
After a long series of annoying attempts I solved the problem placing:
```
jdk:
  - openjdk9
```
in .travis file.
In order to succeed I needed also to comment-out the following:
```
<!--
    <distributionManagement>
        <repository>
            <id>releases-public</id>
            <name>Finalist public releases</name>
            <url>https://nexus.iprofs.nl/content/repositories/releases-public</url>
        </repository>
    </distributionManagement>
    <repositories>
        <repository>
            <id>releases-public</id>
            <name>Finalist public releases</name>
            <url>https://nexus.iprofs.nl/content/repositories/releases-public</url>
        </repository>
    </repositories>
-->
```
in pom.xml file

I would invite you to check travis CI in your original source repository.

**Comment by gvanderploeg** [comment]
Hi Riccardo,

Thanks for analyzing this.
By itself, it's reasonable to upgrade to jdk9. However, the plugin is meant to work on DXP 7.0 and older, so I deem it better that be compiled by travis using jdk 8.
Two related community posts apply, I think:
https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/8
and the real culprit:
https://changelog.travis-ci.com/xenial-as-the-default-build-environment-99476
So I think I'll switch the orginal repo to use ``dist: trusty``

And by the way: you're right about commenting out the nexus repo urls: this is a repo that is not in service anymore. I'll have to fix that as well.

**Comment by gvanderploeg** [comment]
Build by travis succeeds again, will close this issue.
