### ISSUE TITLE
Liferay 7.2 DXP compability

### ISSUE THREAD

**Issue by Maakaapeli** [finalist/liferay-oidc-plugin#47]
Hello!

This maybe a duplicate for https://github.com/finalist/liferay-oidc-plugin/issues/44 but I'd like to know if this plugin is available for 7.2 dpx?

Do you have ETA of release for open idConnectPlugin and does it support gradle workspace or is it still maven project?

Thanks alot!

-Jani

**Comment by gvanderploeg** [comment]
7.2 CE and DXP are considered the same from this plugin's perspective. 
No ETA for the release, I'm sorry. Too busy with other projects right now.
It it based on Maven and will probably not change to Gradle.

**Comment by Maakaapeli** [comment]
Ok, thanks for information! This is now closed.
