### ISSUE TITLE
OAuthProblemException

### ISSUE THREAD

**Issue by uPagge** [finalist/liferay-oidc-plugin#48]
Hi

I am trying to configure oauth 2 on liferay version 7.0.6 GA7. Oauth 2 provider I have spring.

I was able to configure provider itself and 2 clients to it to check that I configured provider correctly. Everything worked, clients also on spring boot.

But when I tried to integrate my provider into liferay using your plugin, I encountered the following problem that I can't solve

![изображение](https://user-images.githubusercontent.com/40397740/79109488-1c767580-7d81-11ea-8b57-d0e664fe305e.png)

![изображение](https://user-images.githubusercontent.com/40397740/79109521-2d26eb80-7d81-11ea-8ec7-2db5a77139d1.png)

**Comment by gvanderploeg** [comment]
Hi,

Set the log level of the package `nl.finalist.liferay` to DEBUG, then you'll see the exact response that the OAuth2 provider sends. Apparently it has another format (or is not 200 OK at all), but you'll only know with logging enabled.

(Control Panel -> Server Administration -> Log levels)

**Comment by uPagge** [comment]
@gvanderploeg 

So I got the code to work. Class LibFilter

![изображение](https://user-images.githubusercontent.com/40397740/79254072-db6b8780-7e8c-11ea-8aaa-7bfa78f1fee2.png)

**Comment by gvanderploeg** [comment]
Hi,

Ok, so basically you added a few specific headers, and an explicit Basic Auth header. Without having delved into the org.apache.oltu.oauth2 code, I would guess that that Basic Auth header is also added by them. And I'm curious what the default Accept and Content-Type headers are when you don't specify them.

**Comment by uPagge** [comment]
@gvanderploeg Is it possible to convey any additional information about the user? For example, user roles

**Comment by gvanderploeg** [comment]
There is no construct available in the plugin for this. There is another issue that suggests to make the access token available to portlets but I'm not really happy with that. But you could write a post login action just like any other in Liferay, and then fetch the OIDC details from the session, just like the LibAutoLogin does already:

    Map<String, String> userInfo = (Map<String, String>) session.getAttribute(
                    LibFilter.OPENID_CONNECT_SESSION_ATTR);
