### ISSUE TITLE
id_token missing

### ISSUE THREAD

**Issue by baldemir** [finalist/liferay-oidc-plugin#5]
I want to use SSO of third party website. Not a known provider like Google or Facebook etc. But when exchanging code with access token, provider doesn't return an id_token. They only return access_token. Is there any way i can use this plugin without id_token.

Thanks in advance.

**Comment by gvanderploeg** [comment]
If they only reply with an access token, then it's not an OpenID Connect-compliant SSO, but sounds more like plain OAuth 2.0. In that case it won't work together.
It could be, however, that you need to supply another scope to get a id_token. Could that be the case?
Maybe consult the documentation of this SSO solution to see whether and how it supports OpenID Connect?
