### ISSUE TITLE
Cannot install from 7.0’s App Store

### ISSUE THREAD

**Issue by scmdavid** [finalist/liferay-oidc-plugin#61]
Cannot install from 7.0’s Control Panel -> App Store. The App Store shown Marketplace login, but the “Sign In” button had no respond.

It there a way to install this plug-in directly?

**Comment by gvanderploeg** [comment]
@scmdavid I'm sorry to say, but I can only confirm that the Marketplace integration of Liferay is severely broken at the moment. We ourselves are also facing this for several installations of plugins.
My suggestion would be to contact Liferay for support on the marketplace integration.

There is no other location where to download the LPKGs at the moment and I'm also not considering that.

**Comment by scmdavid** [comment]
FYI, I finally got the plugin installed from the Market.

I tested Liferay CE 7.0.6 GA 7. The App Store (Marketplace) itself did need an update when it was accessed for the first time. However, after that, I could install the plugin and found the configuration page.
