### ISSUE TITLE
Problem with Default Landing Page 

### ISSUE THREAD

**Issue by jotaceperez** [finalist/liferay-oidc-plugin#9]
Hi,

I have a problem when setting the default Landing Page parameter in liferay, using the login mechanism of liferay is correctly redirected to Default Landing Page, however when I incorporate the component oidc-plugin takes me to the default page and not to The page that I configured (I did it with a new site with a private page), being that the expected behavior is to redirect where I have configured.

I expect any support, while I am investigating how the plugin can influence this misconduct.

Best regards,

**Comment by gvanderploeg** [comment]
As far as I remember, the oidc-plugin does not interfere with the Default Landing Page-setting in the control panel. Maybe it's a permission thing? Does the authenticated user have access to the particular site/page at all?

**Comment by jotaceperez** [comment]
The user authenticated have all permisions to view the site/page, if I try to access to this page using url or navigation menu I can access without problems.

**Comment by gvanderploeg** [comment]
Cannot reproduce, will close for now
